import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const WORKER_PATH = "node_modules/pdfjs-dist/build/pdf.worker.min.mjs";
const OUT_PATH = "src/generated/pdf-worker-source.ts";

const source: string = readFileSync(WORKER_PATH, "utf8");
const banner: string =
  "// Generated by scripts/gen-worker-source.ts — do not edit.\n" +
  "// Inlines pdfjs-dist/build/pdf.worker.min.mjs for same-origin blob workers.\n" +
  "// Regenerate after bumping pdfjs-dist: node scripts/gen-worker-source.ts\n";
const out: string = `${banner}export const PDF_WORKER_SOURCE = ${JSON.stringify(source)};\n`;
mkdirSync("src/generated", { recursive: true });
writeFileSync(OUT_PATH, out);
console.log(`wrote ${OUT_PATH} (${(out.length / 1024 / 1024).toFixed(2)} MB)`);
