import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PDFJS_DIST = "node_modules/pdfjs-dist";
const OUT_PATH = "src/generated/pdf-assets.ts";

// Categories served to pdf.js through the in-memory BinaryDataFactory.
// Each entry: directory, filename filter, license file to reference.
const GROUPS = [
  {
    dir: "cmaps",
    match: (name: string) => name.endsWith(".bcmap"),
    license: "cmaps/LICENSE (Adobe)",
  },
  {
    dir: "standard_fonts",
    match: (name: string) => name.endsWith(".pfb") || name.endsWith(".ttf"),
    license: "standard_fonts/LICENSE_FOXIT, standard_fonts/LICENSE_LIBERATION",
  },
  {
    dir: "wasm",
    match: (name: string) => name === "jbig2.wasm" || name === "openjpeg.wasm",
    license: "wasm/LICENSE_PDFJS_JBIG2, wasm/LICENSE_OPENJPEG",
  },
];

interface Asset {
  name: string;
  data: Buffer;
}

const assets: Asset[] = [];
const licenses: string[] = [];

for (const group of GROUPS) {
  const dir = join(PDFJS_DIST, group.dir);
  const names = readdirSync(dir).filter(group.match).sort();
  if (names.length === 0) {
    throw new Error(`no assets found in ${dir}`);
  }
  for (const name of names) {
    assets.push({ name, data: readFileSync(join(dir, name)) });
  }
  licenses.push(group.license);
}

// Concatenate into one archive; index maps name -> [start, end) byte range.
const index: Array<[string, number, number]> = [];
let offset = 0;
for (const asset of assets) {
  index.push([asset.name, offset, offset + asset.data.length]);
  offset += asset.data.length;
}
const archive = Buffer.concat(assets.map((a) => a.data));
const b64 = archive.toString("base64");

const banner =
  "// Generated by scripts/gen-pdf-assets.ts — do not edit.\n" +
  "// Inlines pdfjs-dist CMaps, standard fonts and (jbig2/openjpeg) wasm so PDF\n" +
  "// rendering needs no external asset URLs (see docs/adr/ADR-1).\n" +
  "// Upstream licenses: " +
  licenses.join("; ") +
  "\n" +
  "// Regenerate after bumping pdfjs-dist: node scripts/gen-pdf-assets.ts\n";

const indexLiteral = index
  .map(([name, start, end]) => `  [${JSON.stringify(name)}, ${start}, ${end}],`)
  .join("\n");

const out =
  banner +
  "// Byte offsets are [start, end) into the decoded PDF_ASSETS_B64 archive.\n" +
  `export const PDF_ASSET_INDEX = [\n${indexLiteral}\n] as const;\n\n` +
  `export const PDF_ASSETS_B64 = ${JSON.stringify(b64)};\n`;

mkdirSync("src/generated", { recursive: true });
writeFileSync(OUT_PATH, out);

const rawKb = (archive.length / 1024).toFixed(0);
const b64Kb = (b64.length / 1024).toFixed(0);
console.log(`wrote ${OUT_PATH}: ${assets.length} assets, ${rawKb} KB raw, ${b64Kb} KB base64`);
