import { deflateSync } from "node:zlib";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { chromium } from "playwright";

mkdirSync("test/fixtures", { recursive: true });

// ── PNG: solid-color pixel grid ─────────────────────────────────
const CRC_TABLE = new Int32Array(256);
for (let n = 0; n < 256; n++) {
  let c = n;
  for (let k = 0; k < 8; k++) {
    c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  }
  CRC_TABLE[n] = c;
}

function crc32(buf: Buffer): number {
  let crc = -1;
  for (const byte of buf) {
    const idx = (crc ^ byte) & 0xff;
    crc = (crc >>> 8) ^ (CRC_TABLE[idx] ?? 0);
  }
  return (crc ^ -1) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function makePng(width: number, height: number, r: number, g: number, b: number): Buffer {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // color type RGB
  const raw = Buffer.alloc(height * (1 + width * 3));
  for (let y = 0; y < height; y++) {
    const row = y * (1 + width * 3);
    raw[row] = 0; // filter none
    for (let x = 0; x < width; x++) {
      raw[row + 1 + x * 3] = r;
      raw[row + 2 + x * 3] = g;
      raw[row + 3 + x * 3] = b;
    }
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", deflateSync(raw)),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

writeFileSync("test/fixtures/tiny.png", makePng(32, 32, 200, 30, 30));

// ── JPEG: gradient, rendered by headless Chromium ───────────────
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 200, height: 200 } });
await page.goto("about:blank");
const dataUrl: string = await page.evaluate(() => {
  const canvas = document.createElement("canvas");
  canvas.width = 64;
  canvas.height = 64;
  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("2D context unavailable");
  }
  const grad = ctx.createLinearGradient(0, 0, 64, 64);
  grad.addColorStop(0, "#2040c0");
  grad.addColorStop(1, "#80d0ff");
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, 64, 64);
  return canvas.toDataURL("image/jpeg");
});
await browser.close();
writeFileSync("test/fixtures/tiny.jpg", Buffer.from(dataUrl.split(",")[1] ?? "", "base64"));

// ── PDF: 2 pages with visible text ──────────────────────────────
function makeTwoPagePdf(): Buffer {
  const objects: Buffer[] = [];
  objects[1] = Buffer.from("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
  objects[2] = Buffer.from("2 0 obj\n<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>\nendobj\n");
  objects[3] = Buffer.from(
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>\nendobj\n",
  );
  objects[4] = Buffer.from(
    "4 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << /Font << /F1 5 0 R >> >> /Contents 7 0 R >>\nendobj\n",
  );
  objects[5] = Buffer.from(
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  );
  const stream1 = Buffer.from("BT /F1 24 Tf 40 100 Td (Page 1) Tj ET\n");
  objects[6] = Buffer.concat([
    Buffer.from(`6 0 obj\n<< /Length ${stream1.length} >>\nstream\n`),
    stream1,
    Buffer.from("endstream\nendobj\n"),
  ]);
  const stream2 = Buffer.from("BT /F1 24 Tf 40 100 Td (Page 2) Tj ET\n");
  objects[7] = Buffer.from(
    `7 0 obj\n<< /Length ${stream2.length} >>\nstream\n${stream2.toString("binary")}endstream\nendobj\n`,
  );

  const chunks: Buffer[] = [Buffer.from("%PDF-1.4\n")];
  const offsets: number[] = [0];
  for (let i = 1; i < objects.length; i++) {
    offsets[i] = chunks.reduce((sum, c) => sum + c.length, 0);
    chunks.push(objects[i] as Buffer);
  }
  const xrefOffset = chunks.reduce((sum, c) => sum + c.length, 0);
  let xref = "xref\n0 8\n0000000000 65535 f \n";
  for (let i = 1; i <= 7; i++) {
    xref += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  xref += `trailer\n<< /Size 8 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  chunks.push(Buffer.from(xref));
  return Buffer.concat(chunks);
}

writeFileSync("test/fixtures/two-page.pdf", makeTwoPagePdf());

// ── Base64 module for tests (node, happy-dom and browser) ───────
const b64 = (p: string): string => readFileSync(p).toString("base64");
writeFileSync(
  "test/fixtures/files.ts",
  `// Generated by scripts/gen-fixtures.ts — do not edit.\n` +
    `export const TINY_PNG_B64 = '${b64("test/fixtures/tiny.png")}'\n` +
    `export const TINY_JPG_B64 = '${b64("test/fixtures/tiny.jpg")}'\n` +
    `export const TWO_PAGE_PDF_B64 = '${b64("test/fixtures/two-page.pdf")}'\n`,
);

console.log("fixtures written: tiny.png, tiny.jpg, two-page.pdf, files.ts");
